# -*- coding: utf-8 -*-
"""ML Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1je-YxwlLiJ8C9aSfSHEcqXgg9zSlYck7

1. RandomForestRegressor
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, classification_report, confusion_matrix
)
from textblob import TextBlob
from sklearn.preprocessing import StandardScaler
import numpy as np

# -----------------------------
# Step 1: Load Dataset
# -----------------------------
df = pd.read_csv("/content/imdb_top_1000.csv", engine='python', on_bad_lines='skip')

# -----------------------------
# Step 2: Feature Engineering
# -----------------------------
df["Sentiment"] = df["Overview"].apply(lambda x: TextBlob(str(x)).sentiment.polarity)
features = ["No_of_Votes", "Sentiment"]
target = "IMDB_Rating"
df.dropna(subset=[target], inplace=True)
X = df[features]
y = df[target]

# -----------------------------
# Step 3: Scaling & Splitting
# -----------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# -----------------------------
# Step 4: Random Forest Regressor
# -----------------------------
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# -----------------------------
# Step 5: Regression Evaluation
# -----------------------------
print("\n🔹 RandomForestRegressor:")
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# -----------------------------
# Step 6: Classification Evaluation
# -----------------------------
def categorize_rating(r):
    if r >= 8.0:
        return "Hit"
    elif r >= 7.0:
        return "Average"
    else:
        return "Flop"

y_test_class = y_test.apply(categorize_rating)
y_pred_class = pd.Series(y_pred).apply(categorize_rating)

print("\n🔹 Classification Metrics:")
print("Accuracy:", accuracy_score(y_test_class, y_pred_class))
print("\nClassification Report:\n", classification_report(y_test_class, y_pred_class))

# Confusion Matrix
cm = confusion_matrix(y_test_class, y_pred_class, labels=["Hit", "Average", "Flop"])
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Hit", "Average", "Flop"],
            yticklabels=["Hit", "Average", "Flop"])
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

# -----------------------------
# Step 7: Regression Visualization
# -----------------------------
plt.figure(figsize=(8, 5))
sorted_indices = np.argsort(y_test.values)
plt.plot(range(len(y_test)), y_test.values[sorted_indices], label="Actual", marker='o', color='blue')
plt.plot(range(len(y_pred)), y_pred[sorted_indices], label="Predicted", marker='x', color='orange', linestyle='--')
plt.title("Actual vs Predicted IMDB_Rating")
plt.xlabel("Sorted Test Sample Index")
plt.ylabel("IMDB_Rating")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""2. DecisionTreeRegressor"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, classification_report, confusion_matrix
)
from textblob import TextBlob
import numpy as np
from sklearn.preprocessing import StandardScaler

# -----------------------------
# Step 1: Load Dataset
# -----------------------------
df = pd.read_csv("/content/imdb_top_1000.csv", engine='python', on_bad_lines='skip')

# -----------------------------
# Step 2: Feature Engineering
# -----------------------------
df["Sentiment"] = df["Overview"].apply(lambda x: TextBlob(str(x)).sentiment.polarity)
features = ["No_of_Votes", "Sentiment"]
target = "IMDB_Rating"
df.dropna(subset=[target], inplace=True)
X = df[features]
y = df[target]

# -----------------------------
# Step 3: Scaling & Split
# -----------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# -----------------------------
# Step 4: Train Decision Tree
# -----------------------------
model = DecisionTreeRegressor(max_depth=5, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# -----------------------------
# Step 5: Regression Evaluation
# -----------------------------
print("\n🔹 Regression Metrics:")
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# -----------------------------
# Step 6: Classification Evaluation
# -----------------------------
def categorize_rating(r):
    if r >= 8.0:
        return "Hit"
    elif r >= 7.0:
        return "Average"
    else:
        return "Flop"

y_test_class = y_test.apply(categorize_rating)
y_pred_class = pd.Series(y_pred).apply(categorize_rating)

print("\n🔹 Classification Metrics (Decision Tree Regressor):")
print("Accuracy:", accuracy_score(y_test_class, y_pred_class))
print("\nClassification Report:\n", classification_report(y_test_class, y_pred_class))

# Confusion Matrix
cm = confusion_matrix(y_test_class, y_pred_class, labels=["Hit", "Average", "Flop"])
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Hit", "Average", "Flop"],
            yticklabels=["Hit", "Average", "Flop"])
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

# -----------------------------
# Step 7: Visualization
# -----------------------------
plt.figure(figsize=(8, 5))
sorted_indices = np.argsort(y_test.values)
plt.plot(range(len(y_test)), y_test.values[sorted_indices], label="Actual", marker='o', color='blue')
plt.plot(range(len(y_pred)), y_pred[sorted_indices], label="Predicted", marker='x', color='orange', linestyle='--')
plt.title("Actual vs Predicted IMDB_Rating")
plt.xlabel("Sorted Test Sample Index")
plt.ylabel("IMDB_Rating")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""3. SVR"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, classification_report
)
from textblob import TextBlob

# -----------------------------
# Step 1: Load Data
# -----------------------------
df = pd.read_csv("/content/imdb_top_1000.csv", engine='python', on_bad_lines='skip')

# -----------------------------
# Step 2: Feature Engineering
# -----------------------------
df["Sentiment"] = df["Overview"].apply(lambda x: TextBlob(str(x)).sentiment.polarity)

features = ["No_of_Votes", "Sentiment"]
target = "IMDB_Rating"

df.dropna(subset=[target], inplace=True)

X = df[features]
y = df[target]

# -----------------------------
# Step 3: Scaling & Split
# -----------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.4, random_state=42
)

# -----------------------------
# Step 4: SVR Model
# -----------------------------
svr = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=0.1)
svr.fit(X_train, y_train)
y_pred = svr.predict(X_test)

# -----------------------------
# Step 5: Regression Evaluation
# -----------------------------
print("\n🔹 SVR Regression Metrics:")
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# -----------------------------
# Step 6: Classification Evaluation
# -----------------------------
def categorize_rating(r):
    if r >= 8.0:
        return "Hit"
    elif r >= 7.0:
        return "Average"
    else:
        return "Flop"

y_test_class = y_test.apply(categorize_rating)
y_pred_class = pd.Series(y_pred).apply(categorize_rating)

print("\n🔹 SVR Classification Metrics:")
print("Accuracy:", accuracy_score(y_test_class, y_pred_class))
print("\nClassification Report:\n", classification_report(y_test_class, y_pred_class))

# Confusion Matrix Visualization
cm = confusion_matrix(y_test_class, y_pred_class, labels=["Hit", "Average", "Flop"])
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Hit", "Average", "Flop"],
            yticklabels=["Hit", "Average", "Flop"])
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()


# -----------------------------
# Step 7: Visualization
# -----------------------------
plt.figure(figsize=(8, 5))
sorted_indices = np.argsort(y_test.values)
plt.plot(range(len(y_test)), y_test.values[sorted_indices], label="Actual IMDB_Rating", marker='o', color='blue')
plt.plot(range(len(y_pred)), y_pred[sorted_indices], label="SVR Predicted", marker='x', linestyle='--', color='orange')
plt.title("Actual vs Predicted IMDB_Rating (SVR)")
plt.xlabel("Sorted Test Sample Index")
plt.ylabel("IMDB_Rating")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""4. LinearRegression"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    classification_report, accuracy_score
)
from textblob import TextBlob

# -----------------------------
# Step 1: Load Dataset
# -----------------------------
df = pd.read_csv("/content/imdb_top_1000.csv", engine='python', on_bad_lines='skip')

# -----------------------------
# Step 2: Feature Engineering
# -----------------------------
df["Sentiment"] = df["Overview"].apply(lambda x: TextBlob(str(x)).sentiment.polarity)

features = ["No_of_Votes", "Sentiment"]
target = "IMDB_Rating"

# Drop rows with missing target values
df.dropna(subset=[target], inplace=True)

X = df[features]
y = df[target]

# -----------------------------
# Step 3: Scaling & Split
# -----------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# -----------------------------
# Step 4: Linear Regression Model
# -----------------------------
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# -----------------------------
# Step 5: Regression Evaluation
# -----------------------------
print("\nLinear Regression Evaluation:")
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# -----------------------------
# Step 6: Classification Evaluation
# -----------------------------
def categorize_rating(r):
    if r >= 8.0:
        return "Hit"
    elif r >= 7.0:
        return "Average"
    else:
        return "Flop"

# Convert to categorical labels
y_test_class = y_test.apply(categorize_rating)
y_pred_class = pd.Series(y_pred).apply(categorize_rating)

print("\nLinear Regression Evaluation:")
print("Accuracy:", accuracy_score(y_test_class, y_pred_class))
print("\nClassification Report:\n", classification_report(y_test_class, y_pred_class))

# Confusion Matrix Visualization
cm = confusion_matrix(y_test_class, y_pred_class, labels=["Hit", "Average", "Flop"])
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Hit", "Average", "Flop"],
            yticklabels=["Hit", "Average", "Flop"])
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()


# -----------------------------
# Step 7: Visualization
# -----------------------------
plt.figure(figsize=(8, 5))
sorted_indices = np.argsort(y_test.values)
plt.plot(range(len(y_test)), y_test.values[sorted_indices], label="Actual IMDB_Rating", marker='o', color='green')
plt.plot(range(len(y_pred)), y_pred[sorted_indices], label="Linear Regression Predicted", marker='x', linestyle='--', color='red')
plt.title("Actual vs Predicted IMDB_Rating (Linear Regression)")
plt.xlabel("Sorted Test Sample Index")
plt.ylabel("IMDB_Rating")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""5. Logistic Regression"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report, accuracy_score, confusion_matrix
)
from textblob import TextBlob

# -----------------------------
# Step 1: Load Dataset
# -----------------------------
df = pd.read_csv("/content/imdb_top_1000.csv", engine='python', on_bad_lines='skip')

# -----------------------------
# Step 2: Feature Engineering
# -----------------------------
df["Sentiment"] = df["Overview"].apply(lambda x: TextBlob(str(x)).sentiment.polarity)

features = ["No_of_Votes", "Sentiment"]
target = "IMDB_Rating"

# Drop rows with missing target values
df.dropna(subset=[target], inplace=True)

# Categorize ratings for classification
def categorize_rating(r):
    if r >= 8.0:
        return "Hit"
    elif r >= 7.0:
        return "Average"
    else:
        return "Flop"

df["Rating_Class"] = df[target].apply(categorize_rating)

X = df[features]
y = df["Rating_Class"]

# -----------------------------
# Step 3: Scaling & Split
# -----------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# -----------------------------
# Step 4: Logistic Regression Model
# -----------------------------
log_model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
log_model.fit(X_train, y_train)
y_pred = log_model.predict(X_test)

# -----------------------------
# Step 5: Evaluation
# -----------------------------
print("\nLogistic Regression Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Confusion Matrix Visualization
cm = confusion_matrix(y_test, y_pred, labels=["Hit", "Average", "Flop"])
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Hit", "Average", "Flop"],
            yticklabels=["Hit", "Average", "Flop"])
plt.title("Confusion Matrix - Logistic Regression")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

# -----------------------------
# Step 6: Probability Visualization
# -----------------------------
y_prob = log_model.predict_proba(X_test)

plt.figure(figsize=(8,5))
for i, cls in enumerate(log_model.classes_):
    plt.plot(y_prob[:, i], label=f"Predicted Prob - {cls}", marker='o', linestyle='--')

plt.title("Class Prediction Probabilities (Logistic Regression)")
plt.xlabel("Test Sample Index")
plt.ylabel("Probability")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""COMPARISON GRAPHS"""

# Comparison graphs for model metrics
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# 1) Enter the metrics (from your table)
# -----------------------------
metrics = {
    'RandomForestRegressor': {'MAE': 0.214, 'MSE': 0.065, 'R2': -0.015, 'Accuracy': 0.595},
    'DecisionTreeRegressor': {'MAE': 0.200, 'MSE': 0.060, 'R2': 0.051, 'Accuracy': 0.595},
    'SVR (RBF)': {'MAE': 0.202, 'MSE': 0.067, 'R2': 0.155, 'Accuracy': 0.5775},
    'LinearRegression': {'MAE': 0.197, 'MSE': 0.056, 'R2': 0.120, 'Accuracy': 0.585},
    'Logistic Regression (cls)': {'MAE': np.nan, 'MSE': np.nan, 'R2': np.nan, 'Accuracy': 0.555}
}

# Convert to DataFrame
df_metrics = pd.DataFrame(metrics).T
# Ensure numeric (NaNs stay for Logistic Regression metrics)
df_metrics = df_metrics[['MAE','MSE','R2','Accuracy']].astype(float)

# --- optional: round for display
display_df = df_metrics.round(3)
print("Metrics table:\n")
print(display_df)

# -----------------------------
# 2) Single-metric bar charts
# -----------------------------
sns.set(style="whitegrid")  # aesthetic

# helper to plot each metric in its own subplot
fig, axes = plt.subplots(2, 2, figsize=(14,10))
axes = axes.ravel()

# MAE
df_metrics['MAE'].plot(kind='bar', ax=axes[0])
axes[0].set_title('MAE Comparison')
axes[0].set_ylabel('MAE')
axes[0].set_ylim(0, df_metrics['MAE'].max() * 1.3)
axes[0].tick_params(axis='x', rotation=30)

# MSE
df_metrics['MSE'].plot(kind='bar', ax=axes[1])
axes[1].set_title('MSE Comparison')
axes[1].set_ylabel('MSE')
axes[1].set_ylim(0, (df_metrics['MSE'].max() if not np.isnan(df_metrics['MSE'].max()) else 1) * 1.3)
axes[1].tick_params(axis='x', rotation=30)

# R2
df_metrics['R2'].plot(kind='bar', ax=axes[2])
axes[2].set_title('R² Comparison')
axes[2].set_ylabel('R² Score')
axes[2].set_ylim(df_metrics['R2'].min() - 0.1, 1.0)  # allow negative R2 display
axes[2].tick_params(axis='x', rotation=30)

# Accuracy
df_metrics['Accuracy'].plot(kind='bar', ax=axes[3])
axes[3].set_title('Classification Accuracy Comparison')
axes[3].set_ylabel('Accuracy')
axes[3].set_ylim(0,1)
axes[3].tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.show()

# -----------------------------
# 3) Grouped chart for numeric metrics (MAE, MSE, R2) - excludes Accuracy
# -----------------------------
# We'll plot only rows with at least one numeric regression metric
reg_df = df_metrics[['MAE','MSE','R2']].copy()

# Normalize each metric for combined view (optional) — commented out; uncomment if you want normalization
# reg_norm = (reg_df - reg_df.min()) / (reg_df.max() - reg_df.min())

# Plot grouped bars
ax = reg_df.plot(kind='bar', figsize=(12,6))
ax.set_title('Grouped Regression Metrics (MAE, MSE, R²)')
ax.set_ylabel('Value')
ax.set_xticklabels(reg_df.index, rotation=30)
plt.legend(title='Metric')
plt.tight_layout()
plt.show()

# -----------------------------
# 4) Accuracy comparison (separate horizontal bar for emphasis)
# -----------------------------
plt.figure(figsize=(10,4))
df_metrics['Accuracy'].sort_values().plot(kind='barh')
plt.xlabel('Accuracy')
plt.title('Classification Accuracy (All models)')
plt.xlim(0,1)
plt.tight_layout()
plt.show()